<?php

/**
 * @file
 * Contains tcm_paragraphs_extra.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tcm_paragraphs_extra_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tcm_paragraphs_extra module.
    case 'help.page.tcm_paragraphs_extra':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extra paragraphs to our sites') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tcm_paragraphs_extra_theme() {
  return [
    'tcm_paragraphs_extra' => [
      'render element' => 'children',
    ],
  ];
}
